account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (PwdResetForm, UserLoginForm,PwdResetConfirmForm)

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html', form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>)/', views.account_activate, name='activate'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/user/delete_confirm.html"), name='delete_confirmation'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html", success_url='password_reset_email_confirm', email_template_name='account/user/password_reset_email.html', form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html', success_url='/account/password_reset_complete/', form_class=PwdResetConfirmForm), name='password_reset_confirm'),
    path('password_reset/password_reset_email_confirm/', TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/', TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),
    #Wishlist
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"),
    path("wishlist", views.wishlist, name="wishlist"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipe.urls', namespace='recipe')),
    path('account/', include('account.urls', namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe/urls.py
from django.urls import path
from . import views

app_name = "recipe"

urlpatterns = [
    path('', views.all_recipes, name='all_recipes'),
    path('<slug:slug>', views.recipe_detail, name='recipe_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
    path('<slug:recipe_slug>/view_recipe_details/', views.view_recipe, name="view_recipe"),

]

recipe/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.conf import settings


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('recipe:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Recipe(models.Model):
    category = models.ForeignKey(Category, related_name='recipe', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='recipe_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/')
    slug = models.SlugField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    users_wishlist = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_wishlist", blank=True)
    recipe_data = models.JSONField(default=dict)

    class Meta:
        verbose_name_plural = 'Recipes'
        ordering = ('-created',)


    def get_absolute_url(self):
        return reverse('recipe:recipe_detail', args=[self.slug])


    def __str__(self):
        return self.title

recipe/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.

from .models import Category, Recipe
from django.http import JsonResponse


def all_recipes(request):
    totalrecipes = Recipe.objects.all() # Select all from recipes (equivalent in SQL)
    print("recipes", totalrecipes)
    return render(request, 'recipe/home.html', {'recipes': totalrecipes})

def recipe_detail(request, slug):
    # get individual item from db. 
    recipe = get_object_or_404(Recipe, slug=slug)
    return render(request, 'recipes/detail.html', {
        'recipe': recipe
    })

def view_recipe(request, recipe_slug):
    # get individual item from db. 
    print("slug", recipe_slug)
    recipe = Recipe.objects.get(id = recipe_slug)
    print("recipe for view recipe", recipe)
    return render(request, 'recipes/view_recipe.html', {
        'recipe': recipe, "recipe_data": recipe.recipe_data})

def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    recipes = Recipe.objects.filter(category = category)
    return render(request, 'recipes/category.html', {'category': category, 'recipes': recipes})

templates/recipe/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'core/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'wishlist/css/wishlist.css' %}">

</head>

<body>
    <header class="pb-3">
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
            <div class="container-fluid px-md-4">
                <div class="d-flex w-100 navbar-collapse">
                    <a class="navbar-brand d-flex-inline" href="/">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hourglass-split" viewBox="0 0 16 16">
                        <path d="M2.5 15a.5.5 0 1 1 0-1h1v-1a4.5 4.5 0 0 1 2.557-4.06c.29-.139.443-.377.443-.59v-.7c0-.213-.154-.451-.443-.59A4.5 4.5 0 0 1 3.5 3V2h-1a.5.5 0 0 1 0-1h11a.5.5 0 0 1 0 1h-1v1a4.5 4.5 0 0 1-2.557 4.06c-.29.139-.443.377-.443.59v.7c0 .213.154.451.443.59A4.5 4.5 0 0 1 12.5 13v1h1a.5.5 0 0 1 0 1h-11zm2-13v1c0 .537.12 1.045.337 1.5h6.326c.216-.455.337-.963.337-1.5V2h-7zm3 6.35c0 .701-.478 1.236-1.011 1.492A3.5 3.5 0 0 0 4.5 13s.866-1.299 3-1.48V8.35zm1 0v3.17c2.134.181 3 1.48 3 1.48a3.5 3.5 0 0 0-1.989-3.158C8.978 9.586 8.5 9.052 8.5 8.351z"/>
                        </svg>
                    </a>
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle d-none d-md-block fw500" href="#" id="navbarDropdown"
                                role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Categories
                            </a>
                            <ul class="dropdown-menu rounded-0 border-0" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url "recipe:all_recipes" %}">All</a></li>
                                {% for c in categories %}
                                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-list" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                    d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
                            </svg>
                        </div>
                        <span class="fs15 fw500"> My Shop</span>
                    </button>

                    {% if user.is_authenticated%}
                    <a type="button" role="button" href="{% url "account:logout" %}"
                        class="btn btn-outline-secondary border-0 basket-btn">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-door-closed" viewBox="0 0 16 16">
                                <path
                                    d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                                <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                            </svg>
                        </div>
                        <span class="fs15 fw500">Logout</span>
                    </a>
                
                    {% else %}
                    <a type="button" role="button" href="{% url "account:login"%}"
                        class="btn btn-outline-secondary border-0 basket-btn">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-door-closed" viewBox="0 0 16 16">
                                <path
                                    d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                                <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                            </svg>
                        </div>
                        <span class="fs15 fw500">Login</span>
                    </a>
                    {% endif %}


                    <a type="button" role="button" href="{% url "account:dashboard" %}" 
                        class="btn btn-outline-secondary border-0 basket-btn">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                                class="bi bi-person" viewBox="0 0 16 16">
                                <path
                                    d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                            </svg>
                        </div>
                        <span class="fs15 fw500">Account</span>
                    </a>

                </div>
                <div class="d-md-none d-lg-none d-xl-none">
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            <li><a class="dropdown-item" href="{% url "recipe:all_recipes" %}">All</a></li>
                            {% for c in categories %}
                            <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                                <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <form class="d-flex w-100 d-md-none">
                    <input class="form-control me-2" type="search" placeholder="Search products or FAQ"
                        aria-label="Search">
                    <button class="btn btn-outline-secondary" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>

    <div id="content">{% block content %} {% endblock %}</div>

    <footer class="container py-5 footer">
        <hr>
        <div class="row pt-4">
            <div class="col-12 col-md">
                <small class="d-block mb-3 text-muted">&copy; 2017-2021</small>
            </div>
            <div class="col-6 col-md fs15">
                <h5>Features</h5>
                <ul class="list-unstyled">
                    <li><a class="link-secondary text-decoration-none" href="#">Cool stuff</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Random feature</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Team feature</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Stuff for developers</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Another one</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Last time</a></li>
                </ul>
            </div>
            <div class="col-6 col-md fs15">
                <h5>Resources</h5>
                <ul class="list-unstyled">
                    <li><a class="link-secondary text-decoration-none" href="#">Resource name</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Resource</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Another resource</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Final resource</a></li>
                </ul>
            </div>
            <div class="col-6 col-md fs15">
                <h5>Resources</h5>
                <ul class="list-unstyled">
                    <li><a class="link-secondary text-decoration-none" href="#">Business</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Education</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Government</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Gaming</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>About</h5>
                <ul class="list-unstyled">
                    <li><a class="link-secondary text-decoration-none" href="#">Team</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Locations</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Privacy</a></li>
                    <li><a class="link-secondary text-decoration-none" href="#">Terms</a></li>
                </ul>
            </div>
        </div>
    </footer>
</body>

</html>

templates/recipe/home.html
{% extends "./base.html" %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content %}


<main>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">All Recipes</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for recipe in recipes %}

        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" alt="Responsive image" src="{{ recipe.image.url }}">
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ recipe.get_absolute_url }}">{{ recipe.title }}</a>
              </p>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}