account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (PwdResetForm, UserLoginForm,PwdResetConfirmForm)

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html', form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>)/', views.account_activate, name='activate'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/user/delete_confirm.html"), name='delete_confirmation'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html", success_url='password_reset_email_confirm', email_template_name='account/user/password_reset_email.html', form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html', success_url='/account/password_reset_complete/', form_class=PwdResetConfirmForm), name='password_reset_confirm'),
    path('password_reset/password_reset_email_confirm/', TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/', TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),
    #Wishlist
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"),
    path("wishlist", views.wishlist, name="wishlist"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipe.urls', namespace='recipe')),
    path('account/', include('account.urls', namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe/urls.py
from django.urls import path
from . import views

app_name = "recipe"

urlpatterns = [
    path('', views.all_recipes, name='all_recipes'),
    path('<slug:slug>', views.recipe_detail, name='recipe_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
    path('<slug:recipe_slug>/view_recipe_details/', views.view_recipe, name="view_recipe"),

]

recipe/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.conf import settings


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('recipe:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Recipe(models.Model):
    category = models.ForeignKey(Category, related_name='recipe', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='recipe_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/')
    slug = models.SlugField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    users_wishlist = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_wishlist", blank=True)
    recipe_data = models.JSONField(default=dict)

    class Meta:
        verbose_name_plural = 'Recipes'
        ordering = ('-created',)


    def get_absolute_url(self):
        return reverse('recipe:recipe_detail', args=[self.slug])


    def __str__(self):
        return self.title

recipe/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.

from .models import Category, Recipe
from django.http import JsonResponse


def all_recipes(request):
    totalrecipes = Recipe.objects.all() # Select all from recipes (equivalent in SQL)
    print("recipes", totalrecipes)
    return render(request, 'recipe/home.html', {'recipes': totalrecipes})

def recipe_detail(request, slug):
    # get individual item from db. 
    recipe = get_object_or_404(Recipe, slug=slug)
    return render(request, 'recipes/detail.html', {
        'recipe': recipe
    })

def view_recipe(request, recipe_slug):
    # get individual item from db. 
    print("slug", recipe_slug)
    recipe = Recipe.objects.get(id = recipe_slug)
    print("recipe for view recipe", recipe)
    return render(request, 'recipes/view_recipe.html', {
        'recipe': recipe, "recipe_data": recipe.recipe_data})

def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    recipes = Recipe.objects.filter(category = category)
    return render(request, 'recipes/category.html', {'category': category, 'recipes': recipes})

templates/recipes/category.html
{% extends "recipe/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Recipes{% endif %}
{% endblock %}
{% block content %}


<main>
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">{{category.name|title}}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for recipe in recipes %}

        <div class="col">
          <div class="card shadow-sm">
          <img class="img-fluid" alt="Responsive image" src="{{ recipe.image.url }}">

            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ recipe.get_absolute_url }}">{{ recipe.title }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">9min read</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

templates/recipes/detail.html
{% extends "recipe/base.html" %}
{% load static %}
{% block title %}
{{ recipe.name }}
{% endblock %}
{% block content %}
<div class="container">
    {% if messages %}
        <div class="alert alert-warning" alert-{{ message.tags }}" role="alert">
        {% for message in messages  %}
            {{message|safe}} 
        {% endfor %}
        <a type="button" role="button" href="{% url "account:wishlist" %}"
                        class="btn btn-outline-secondary border-0 wishlist-btn">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-emoji-heart-eyes" viewBox="0 0 16 16">
                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                            <path d="M11.315 10.014a.5.5 0 0 1 .548.736A4.498 4.498 0 0 1 7.965 13a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .548-.736h.005l.017.005.067.015.252.055c.215.046.515.108.857.169.693.124 1.522.242 2.152.242.63 0 1.46-.118 2.152-.242a26.58 26.58 0 0 0 1.109-.224l.067-.015.017-.004.005-.002zM4.756 4.566c.763-1.424 4.02-.12.952 3.434-4.496-1.596-2.35-4.298-.952-3.434zm6.488 0c1.398-.864 3.544 1.838-.952 3.434-3.067-3.554.19-4.858.952-3.434z"/>
                            </svg>
                        </div>
                        <span class="fs15 fw500">Click here</span>
        </a>
        </div>
    {% endif %}
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ recipe.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ recipe.title }}</h1>
                <p><span class="lead">{{ recipe.author }}</span> (Author)</p>
                <p>{{ recipe.description|slice:":355" }}...</p>
                <div class="col-4">
                {% if user.is_authenticated%}  
                <div class= "col-xs-4" >
                <a href = "{% url "recipe:view_recipe" recipe.id %}" class="btn btn-light mr-10 " style="margin-bottom:10px;" role="button">See Recipe</a>
                <a href = "{% url "account:user_wishlist" recipe.id %}"class="btn btn-light mr-5" role="button">Add to Wish List</a>
                </div>            
                {% else %}
                    <a href = "{% url "account:login" %}"class="btn btn-light mr-5" role="button">Login to view Recipe</a>

                {% endif %}
                </div>
            </div>
        </div>
    </main>
</div>

{% endblock %}

templates/recipes/view_recipe.html
{% extends "recipe/base.html" %}
{% load static %}
{% block title %}
{{ recipe.name }}
{% endblock %}
{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ recipe.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ recipe.title }}</h1>
                <p><span class="lead">{{ recipe.author }}</span> (Author)</p>
                <p>{{ recipe.description|slice:":355" }}...</p>
                <p>Ingredients:</p>
                {% for ingredient in recipe_data.ingredients  %}
                    <li> {{ingredient}} </li>
                {% endfor %}
            </div>
            <p>Actual Recipe:</p>
                {% for description in recipe_data.recipe_description  %}
                    <dl> {{description}} </dl>
                {% endfor %}
        </div>
    </main>
</div>


{% endblock %}